@startuml
hide footbox

title Angebote ermitteln
actor Client
participant ELI as eli
participant "CRM" as crm

Client -> eli: ermittle Angebote (Vorgangsnummer)
eli --> Client: Angebote
activate Client
Client -> Client: lese zugrundeliegende Daten\naus dem Angebot aus
Client -> crm: update 'data of lead'

@enduml