@startuml
title Angebote ermitteln
actor Client

Client -> ELI: Angebote ermitteln (Vorgang)
ELI --> Client: Angebote

newpage Angebot(e) merken

Client -> "Vorgaenge-API": Vorgang anlegen
"Vorgaenge-API" -> Core: Vorgang anlegen
Core --> "Vorgaenge-API": vorgangsNummer
"Vorgaenge-API" --> Client: vorgangsNummer

Client -> "Vorgaenge-API": Erfasste Daten speichern (vorgangsNummer)

Client -> ELI: Angebote ermitteln (vorgangsNummer)
ELI -> "Vorgaenge-API": getVorgang (vorgangsNummer)
"Vorgaenge-API" --> ELI: Vorgang
ELI -> ELI: Angebote ermitteln (Vorgang)
ELI --> Client: Angebote

Client [#00AA00]-> "Vorgaenge-API": merke Angebot (vorgangsNummer?,angebotsId,mId?)
note right: Evtl. eigener Merken Service
"Vorgaenge-API" -> ELI: getAngebot (angebotsId)
ELI --> "Vorgaenge-API": Angebot
"Vorgaenge-API" [#00AA00]-> Core: speichere Angebot (vorgangsNummer,Angebot)
Core --> "Vorgaenge-API": angebotId
"Vorgaenge-API" --> Client: Id gemerktes Angebot (mId)

newpage Angebot aktualisieren

Client [#00AA00]-> "Vorgaenge-API": aktualisiere Angebot (mId)
"Vorgaenge-API" [#00AA00]-> Core: getGemerktesAngebot(angebotsId)
Core -[#00AA00]-> "Vorgaenge-API": Angebot
"Vorgaenge-API" [#00AA00]-> "Vorgaenge-API": holeErfassteDaten und PA aus Angebot
"Vorgaenge-API" [#00AA00]-> ELI: Angebote ermitteln (erfassteDaten, Produktanbieter)
ELI -[#00AA00]-> "Vorgaenge-API" : aktualisiertes Angebot

"Vorgaenge-API" [#00AA00]-> Core: speichere Angebot (BTVId,Angebot, zugrundeliegendeAngebotsId)
"Vorgaenge-API" -[#00AA00]-> Client : aktualisiertes Angebot

newpage Gegenangebot

@enduml