@startuml

hide footbox

title Angebot merken

actor Client as client
participant "ELI" as eli
participant "Vorgänge API" as vorgaenge_api

client -> eli: ermittle Angebote (Vorgangsnummer)

eli --> client: ermittelte Angebote mit AngebotsIds


client -> vorgaenge_api: merke Angebot (Vorgangsnummer, angebotsId)

vorgaenge_api --> client: gemerkte AngebotsId & AngebotsURL

@enduml