@startuml

hide footbox

title Angebot entmerken

actor Client as client


box "Interne Aufrufe" #LightBlue
  participant "Vorgänge API" as vorgaenge_api
  participant "Core" as core
end box



hide footbox

|||
client -> vorgaenge_api: entmerke Angebot (Vorgangsnummer,'mid')
vorgaenge_api -> core: lösche Angebot (Vorgangsnummer,'mid')


@enduml