@startuml

hide footbox

title Angebot merken

box "Interne Aufrufe" #LightBlue
  participant "Vorgänge API" as vorgaenge_api
  participant "Core" as core
end box

actor Client as client
participant "ELI" as eli

box "Interne Aufrufe" #LightBlue
  participant "Vorgänge API" as vorgaenge_api
  participant "Core" as core
end box

client [#00AA00]-> eli: ermittle Angebote (POST, Anfrage: 'ErfassteDaten' )
activate eli
eli [#00AA00]--> client: Angebote
deactivate eli

client -> vorgaenge_api: erzeuge Vorgang
activate vorgaenge_api
vorgaenge_api -> core: erzeuge Vorgang
core --> vorgaenge_api:  Vorgangsnummer
vorgaenge_api --> client: Vorgangsnummer
client -> vorgaenge_api: Erfasste Daten speichern (Vorgangsnummer)
client -> vorgaenge_api: merke Angebot (Vorgangsnummer,angebotsId,(optionale 'gemerkteAngebotsId'))
vorgaenge_api -> eli: lese Angebot (angebotsId)
activate eli
eli --> vorgaenge_api: Angebot
deactivate eli
vorgaenge_api -> core: speichere Angebot (Vorgangsnummer,Angebot, 'gemerkteAngebotsId')
core --> vorgaenge_api: gemerkteAngebotsId
deactivate vorgaenge_api
vorgaenge_api --> client: gemerkteAngebotsId

@enduml