@startuml
title Usecase Diagramme

left to right direction
skinparam packageStyle rectangle
actor Client as client

rectangle  {
  (Angebote ermitteln) as ermitteln
  client -- ermitteln
  (Angebot merken) as merken
  client -- merken
  'merken .> ermitteln: include

  ( Angebot entmerken ) as entmerken
  client -- entmerken
  'entmerken .> ermitteln: include
  ( Angebot aktualisieren ) as aktualsieren
  client -- aktualsieren
  'aktualsieren .> ermitteln: include
  client -- ( gemerkte Angebote auslesen )

  client -- ( Unterlagenliste des Gegenangebots ermitteln )
}

@enduml